# Generated by Django 2.1.7 on 2019-03-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='formatted_phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
