# Generated by Django 2.1.7 on 2019-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmap', '0002_auto_20190319_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='open_now',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
