# Generated by Django 2.1.7 on 2019-03-20 08:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubmap', '0005_auto_20190320_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='opening_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
