# Generated by Django 2.1.7 on 2019-03-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubmap', '0007_auto_20190320_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'spokojnie usiądziesz'), (2, 'pośpiesz się'), (3, 'jak masz szczęście, to coś znajdziesz'), (4, 'przygotuj się na stanie'), (5, 'nawet nie wejdziesz')])),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubmap.Pub')),
            ],
        ),
    ]
