# Generated by Django 2.1.7 on 2019-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmap', '0009_auto_20190320_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'spokojnie usiądziesz'), (2, 'pośpiesz się'), (3, 'jak masz szczęście, to coś znajdziesz'), (4, 'postoisz'), (5, 'nawet nie wejdziesz')]),
        ),
    ]
